mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
hosts:
  .googleapis.cn: 142.250.196.131
  .google.cn: 142.250.196.131
proxies:
  - {name: "[VMess] å‰æ—çœ ç§»åŠ¨(å…¨çœé€šç”¨)", server: 111.26.109.79, port: 30829, type: vmess, uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484, alterId: 2, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /oooo}, udp: true, tfo: false}
  - {name: "[VMess] ğŸ‡¨ğŸ‡¦ _CA_åŠ æ‹¿å¤§", server: 108.181.10.17, port: 80, type: vmess, uuid: 474e8680-701f-11ee-b436-205c6d5f5d78, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /}, udp: true, tfo: false}
  - {name: "[VMess] ğŸ‡®ğŸ‡· ä¼Šæœ— å¾·é»‘å…°å¸‚", server: 78.39.9.134, port: 8090, type: vmess, uuid: 891e1d1c-5fbc-40cb-9256-58b016b6b600, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, udp: true, tfo: false}
  - {name: "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹", server: xcvBnMjKi.999824.xyZ, port: 443, type: vmess, uuid: 512d9674-db12-44ca-a1b5-654244549b65, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /uiAxvH6OkVk0VCfa7dX3JIrYk7zm, headers: {Host: xcvBnMjKi.999824.xyZ}}, udp: true, tfo: false}
  - {name: "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 2", server: 104.21.112.1, port: 2096, type: vmess, uuid: b3928f8d-ea81-4d75-bcec-4016a072adff, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: de01.sh-cloudflare.sbs}}, udp: true, tfo: false}
  - {name: "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 3", server: us01.sh-cloudflare.sbs, port: 8443, type: vmess, uuid: 2bd0c9d7-f239-437e-a1e1-6cf830af2a1a, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: us01.sh-cloudflare.sbs}}, udp: true, tfo: false}
  - {name: "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 4", server: 104.17.176.171, port: 8080, type: vmess, uuid: 6cbc9c78-1cb1-57d4-a999-e2f4e34c1e03, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /nasnet/cdn, headers: {Host: ke7hz36ewz-4515017473.mashallahbet.com}}, udp: true, tfo: false}
proxy-groups:
  - name: ğŸš€ å…¨çƒäº’è”
    type: select
    proxies:
      - ğŸš€ å…¨éƒ¨èŠ‚ç‚¹
  - name: ğŸš€ å…¨éƒ¨èŠ‚ç‚¹
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡ºğŸ‡² ç¾å›½
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - "[VMess] å‰æ—çœ ç§»åŠ¨(å…¨çœé€šç”¨)"
      - "[VMess] ğŸ‡¨ğŸ‡¦ _CA_åŠ æ‹¿å¤§"
      - "[VMess] ğŸ‡®ğŸ‡· ä¼Šæœ— å¾·é»‘å…°å¸‚"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 2"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 3"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 4"
  - name: ğŸ¥ Netflix
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡ºğŸ‡² ç¾å›½
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - "[VMess] å‰æ—çœ ç§»åŠ¨(å…¨çœé€šç”¨)"
      - "[VMess] ğŸ‡¨ğŸ‡¦ _CA_åŠ æ‹¿å¤§"
      - "[VMess] ğŸ‡®ğŸ‡· ä¼Šæœ— å¾·é»‘å…°å¸‚"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 2"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 3"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 4"
  - name: ğŸ“¹ Youtube
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡ºğŸ‡² ç¾å›½
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - "[VMess] å‰æ—çœ ç§»åŠ¨(å…¨çœé€šç”¨)"
      - "[VMess] ğŸ‡¨ğŸ‡¦ _CA_åŠ æ‹¿å¤§"
      - "[VMess] ğŸ‡®ğŸ‡· ä¼Šæœ— å¾·é»‘å…°å¸‚"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 2"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 3"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 4"
  - name: â–¶ï¸ Disney+
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡ºğŸ‡² ç¾å›½
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - "[VMess] å‰æ—çœ ç§»åŠ¨(å…¨çœé€šç”¨)"
      - "[VMess] ğŸ‡¨ğŸ‡¦ _CA_åŠ æ‹¿å¤§"
      - "[VMess] ğŸ‡®ğŸ‡· ä¼Šæœ— å¾·é»‘å…°å¸‚"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 2"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 3"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 4"
  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸš€ å…¨çƒäº’è”
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡ºğŸ‡² ç¾å›½
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - "[VMess] å‰æ—çœ ç§»åŠ¨(å…¨çœé€šç”¨)"
      - "[VMess] ğŸ‡¨ğŸ‡¦ _CA_åŠ æ‹¿å¤§"
      - "[VMess] ğŸ‡®ğŸ‡· ä¼Šæœ— å¾·é»‘å…°å¸‚"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 2"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 3"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 4"
  - name: ğŸ“² Telegram
    type: select
    proxies:
      - ğŸš€ å…¨çƒäº’è”
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡ºğŸ‡² ç¾å›½
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  - name: ğŸŒ å›½å†…åª’ä½“
    type: select
    proxies:
      - DIRECT
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡ºğŸ‡² ç¾å›½
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - "[VMess] å‰æ—çœ ç§»åŠ¨(å…¨çœé€šç”¨)"
      - "[VMess] ğŸ‡¨ğŸ‡¦ _CA_åŠ æ‹¿å¤§"
      - "[VMess] ğŸ‡®ğŸ‡· ä¼Šæœ— å¾·é»‘å…°å¸‚"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 2"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 3"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 4"
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯
    type: select
    proxies:
      - DIRECT
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬
    type: select
    proxies:
      - DIRECT
  - name: ğŸ‡ºğŸ‡² ç¾å›½
    type: select
    proxies:
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 2"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 3"
      - "[VMess] ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹ 4"
  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾
    type: select
    proxies:
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
    type: select
    proxies:
      - DIRECT
  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - DIRECT
      - ğŸš€ å…¨çƒäº’è”
script:
  shortcuts:
    bilibilishit: any([word in host for word in ['biliapi', 'bilibili']]) and any([word in host for word in ['-live-tracker-', 'p2p', 'pcdn']])
    douyushit: (network == 'udp' or 'p2p' in host) and 'douyu' in host
rules:
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - DOMAIN,downloads.ti.com,DIRECT
  - DOMAIN,cdn.bootcdn.net,DIRECT
  - DOMAIN,crl4.digicert.com,DIRECT
  - DOMAIN,ocsp.digicert.com,DIRECT
  - DOMAIN,statusf.digitalcertvalidation.com,DIRECT
  - DOMAIN,ocsp.verisign.com,DIRECT
  - DOMAIN,static.assetlab.io,DIRECT
  - DOMAIN,stats.114515.best,DIRECT
  - DOMAIN-KEYWORD,1drv,â“‚ï¸ å¾®è½¯æœåŠ¡
  - DOMAIN-KEYWORD,microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - DOMAIN,alt1-mtalk.google.com,DIRECT
  - DOMAIN,alt2-mtalk.google.com,DIRECT
  - DOMAIN,alt3-mtalk.google.com,DIRECT
  - DOMAIN,alt4-mtalk.google.com,DIRECT
  - DOMAIN,alt5-mtalk.google.com,DIRECT
  - DOMAIN,alt6-mtalk.google.com,DIRECT
  - DOMAIN,alt7-mtalk.google.com,DIRECT
  - DOMAIN,alt8-mtalk.google.com,DIRECT
  - DOMAIN,mtalk.google.com,DIRECT
  - IP-CIDR,64.233.177.188/32,DIRECT,no-resolve
  - IP-CIDR,64.233.186.188/32,DIRECT,no-resolve
  - IP-CIDR,64.233.187.188/32,DIRECT,no-resolve
  - IP-CIDR,64.233.188.188/32,DIRECT,no-resolve
  - IP-CIDR,64.233.189.188/32,DIRECT,no-resolve
  - IP-CIDR,74.125.23.188/32,DIRECT,no-resolve
  - IP-CIDR,74.125.24.188/32,DIRECT,no-resolve
  - IP-CIDR,74.125.28.188/32,DIRECT,no-resolve
  - IP-CIDR,74.125.127.188/32,DIRECT,no-resolve
  - IP-CIDR,74.125.137.188/32,DIRECT,no-resolve
  - IP-CIDR,74.125.203.188/32,DIRECT,no-resolve
  - IP-CIDR,74.125.204.188/32,DIRECT,no-resolve
  - IP-CIDR,74.125.206.188/32,DIRECT,no-resolve
  - IP-CIDR,108.177.125.188/32,DIRECT,no-resolve
  - IP-CIDR,142.250.4.188/32,DIRECT,no-resolve
  - IP-CIDR,142.250.10.188/32,DIRECT,no-resolve
  - IP-CIDR,142.250.31.188/32,DIRECT,no-resolve
  - IP-CIDR,142.250.96.188/32,DIRECT,no-resolve
  - IP-CIDR,172.217.194.188/32,DIRECT,no-resolve
  - IP-CIDR,172.217.218.188/32,DIRECT,no-resolve
  - IP-CIDR,172.217.219.188/32,DIRECT,no-resolve
  - IP-CIDR,172.253.63.188/32,DIRECT,no-resolve
  - IP-CIDR,172.253.122.188/32,DIRECT,no-resolve
  - IP-CIDR,173.194.175.188/32,DIRECT,no-resolve
  - IP-CIDR,173.194.218.188/32,DIRECT,no-resolve
  - IP-CIDR,209.85.233.188/32,DIRECT,no-resolve
  - DOMAIN,aefd.nelreports.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,ftp.fau.de,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,legendspatch-lol.cdn.x-cdn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,opgg-desktop-patch.akamaized.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,opgg-desktop-data.akamaized.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,opgg-static.akamaized.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,opggsupport.zendesk.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,epicgames-download1.akamaized.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,fastly-download.epicgames.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,download.epicgames.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,download2.epicgame.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,download3.epicgames.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,download4.epicgames.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,cloudflare.epicgamescdn.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,nrk-od-world-52.akamaized.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,mirror.cyberbits.eu,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,ftp.lysator.liu.se,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,apt.izzysoft.de,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,zh.savefrom.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,dl.fevr.top,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,download.sysinternals.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,winscp-static-746341.c.cdn77.org,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,edgedl.me.gvt1.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,downloadfiles.idera.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,ftp.ni.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,mirror.ossplanet.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,ftp.agdsn.de,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,debian.map.fastlydns.net,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,cdn.tailwindcss.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,sb.adtidy.org,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,dl-cdn.alpinelinux.org,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,cdn-fastly.obsproject.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,res.lolli.tech,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,download.todesktop.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,plug-mirror.rcac.purdue.edu,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,download.amd.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,i.mij.rip,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,mjj.today,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,ice.frostsky.com,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,image.mooncloud.top,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,i.111666.best,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,image.acg.lol,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,ncs.lnk.to,ğŸŒ å›½å¤–åª’ä½“
  - DOMAIN,rstatus.nxnow.top,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,aagit.yougotme.cc,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,pub-f6afb74f13c64cd89561b4714dca1c27.r2.dev,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,api.leo.moe,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,api.deeplx.org,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,rsshub.app,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,flowerss-bot.now.sh,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,blog.aiservices.tech,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,securepubads.g.doubleclick.net,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,pagead2.googlesyndication.com,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,share.acgnx.se,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,129888.xyz,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,net-tutorials.onfastspring.com,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,immersive-translate.owenyoung.com,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,clash.razord.top,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,yacd.haishan.me,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,yacd.metacubex.one,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,ariang.mayswind.net,ğŸš€ å…¨çƒäº’è”
  - IP-CIDR,35.190.71.189/32,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,rss.nxnow.top,ğŸš€ å…¨çƒäº’è”
  - IP-CIDR,1.1.1.1/32,ğŸš€ å…¨çƒäº’è”
  - IP-CIDR,1.0.0.1/32,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,ws-eu.pusher.com,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,cdn.usefathom.com,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,ai.google.dev,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,makersuite.google.com,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,alkalimakersuite-pa.clients6.google.com,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,labs.google.com,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,aistudio.google.com,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,openaicomproductionae4b.blob.core.windows.net,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,production-openaicom-storage.azureedge.net,ğŸš€ å…¨çƒäº’è”
  - DOMAIN,sdkapi.netmera.com,ğŸš€ å…¨çƒäº’è”
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
